openapi: 3.0.3
info:
  title: Order & Analytics Service API
  description: >
    API for managing orders with complex item types (e.g., Cake)
    and providing analytics insights such as revenue and sales performance.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api

tags:
  - name: Orders
    description: Order management operations
  - name: Analytics
    description: Business intelligence and analytics endpoints

paths:
  /orders:
    post:
      summary: Create a new order
      tags: [Orders]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '201':
          description: Order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'

    get:
      summary: Get all orders
      tags: [Orders]
      responses:
        '200':
          description: List of orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'

  /orders/{orderId}:
    get:
      summary: Get an order by ID
      tags: [Orders]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Order details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found

    put:
      summary: Update an order
      tags: [Orders]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        '200':
          description: Order updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
        '404':
          description: Order not found

    delete:
      summary: Delete an order
      tags: [Orders]
      parameters:
        - name: orderId
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Order deleted successfully

  /analytics/orders/total:
    get:
      summary: Get total number of orders
      tags: [Analytics]
      responses:
        '200':
          description: Total orders count
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TotalOrdersResponse'

  /analytics/orders/by-item-type:
    get:
      summary: Get number of orders per item type
      tags: [Analytics]
      responses:
        '200':
          description: Orders grouped by item type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrdersByItemTypeResponse'

  /analytics/revenue/total:
    get:
      summary: Get total revenue
      tags: [Analytics]
      responses:
        '200':
          description: Total revenue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TotalRevenueResponse'

  /analytics/revenue/by-item-type:
    get:
      summary: Get revenue breakdown by item type
      tags: [Analytics]
      responses:
        '200':
          description: Revenue by item type
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevenueByItemTypeResponse'

  /analytics/items/best-seller:
    get:
      summary: Get best-selling item
      tags: [Analytics]
      responses:
        '200':
          description: Best seller item
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BestSellerResponse'

  /analytics/revenue/weekly:
    get:
      summary: Get revenue per week
      tags: [Analytics]
      parameters:
        - name: week
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Weekly revenue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevenuePerWeekResponse'

  /analytics/revenue/monthly:
    get:
      summary: Get revenue per month
      tags: [Analytics]
      parameters:
        - name: month
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Monthly revenue
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/RevenuePerMonthResponse'

components:
  schemas:
    Order:
      type: object
      properties:
        id:
          type: string
          example: "12345"
        item:
          $ref: '#/components/schemas/OrderItem'
        quantity:
          type: integer
          example: 1
        price:
          type: number
          format: double
          example: 999.99
      required: [item, quantity, price]

    OrderItem:
      type: object
      required: [category, details]
      properties:
        category:
          type: string
          example: Cake
        details:
          oneOf:
            - $ref: '#/components/schemas/Cake'

    Cake:
      type: object
      properties:
        type:
          type: string
        flavor:
          type: string
        filling:
          type: string
        size:
          type: number
        layers:
          type: number
        frostingType:
          type: string
        frostingFlavor:
          type: string
        decorationType:
          type: string
        decorationColor:
          type: string
        customMessage:
          type: string
        shape:
          type: string
        allergies:
          type: string
        specialIngredients:
          type: string
        packagingType:
          type: string
      required: [type, flavor, size]

    TotalOrdersResponse:
      type: object
      properties:
        totalOrders:
          type: integer
          example: 245

    OrdersByItemTypeResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/ItemTypeCount'

    ItemTypeCount:
      type: object
      properties:
        itemType:
          type: string
          example: Cake
        orderCount:
          type: integer
          example: 120

    TotalRevenueResponse:
      type: object
      properties:
        totalRevenue:
          type: number
          format: double
          example: 152340.75

    RevenueByItemTypeResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/ItemTypeRevenue'

    ItemTypeRevenue:
      type: object
      properties:
        itemType:
          type: string
          example: Cake
        revenue:
          type: number
          format: double
          example: 84200.50

    BestSellerResponse:
      type: object
      properties:
        itemType:
          type: string
          example: Cake
        totalOrders:
          type: integer
          example: 120

    RevenuePerWeekResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/WeeklyRevenue'

    WeeklyRevenue:
      type: object
      properties:
        week:
          type: string
          example: "2025-W12"
        revenue:
          type: number
          format: double
          example: 12450.75

    RevenuePerMonthResponse:
      type: object
      properties:
        results:
          type: array
          items:
            $ref: '#/components/schemas/MonthlyRevenue'

    MonthlyRevenue:
      type: object
      properties:
        month:
          type: string
          example: "2025-03"
        revenue:
          type: number
          format: double
          example: 51200.00
